-- MySQL Script generated by MySQL Workbench
-- sáb 04 mar 2023 19:36:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema spotify_albums
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `spotify_albums` ;

-- -----------------------------------------------------
-- Schema spotify_albums
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spotify_albums` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `spotify_albums` ;

-- -----------------------------------------------------
-- Table `spotify_albums`.`spotify_search_history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `spotify_albums`.`spotify_search_history` ;

CREATE TABLE IF NOT EXISTS `spotify_albums`.`spotify_search_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ip_address` VARCHAR(15) NOT NULL,
  `artist_name` VARCHAR(255) NOT NULL,
  `search_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
